[package]
name = "coreutils-rs"
version = "0.1.0"
edition = "2021"
description = "GNU Coreutils package implementation with Rust"
license = "Apache-2.0"
[dependencies]
clap = { version = "4.5.17", features = ["derive"] }